### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by ErickWendel** [TehZarathustra/nodejs-meme-generator#3]
Running npm I results in the following error

```
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/erickwendel/Documents/projetos/cursos/serverless-aws/source/demo05-layer/layer-example/node_modules/canvas
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by TehZarathustra** [comment]
Hey! Make sure you have Cairo and Pango installed
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`

I've assembled the example from readme section, it works on MacOS
